desktop:
  icon: icon-laptop.svg
  link:
    type: external

mobile:
  icon: icon-phone.svg
  link:
    type: external

cozy-collect:
  icon: icon-bills.svg
  link:
    type: apps
    appSlug: collect
    path: '#/discovery/?intro'

support:
  icon: icon-question-mark.svg
  link:
    type: external
